/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
*/

// import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.earth.geometry} material={materials.earth} rotation={[3.089, 1.037, -2.646]} scale={10} />
      <mesh geometry={nodes.clouds.geometry} material={materials.clouds} rotation={[2.818, -0.166, -2.132]} />
      <mesh geometry={nodes.atmo.geometry} material={materials.atmo} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
